version: "3.5"
services:

  postgresql:
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:13
    networks:
      - temporal-network
    expose:
      - "5432"

  temporal:
    container_name: temporal
    depends_on:
      - postgresql
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=temporal.yaml
    image: temporalio/auto-setup:1.16.1
    networks:
      - temporal-network
    expose:
      - "7233"
    volumes:
      - ./temporal.yaml:/etc/temporal/temporal.yaml:z

  temporal-development:
    container_name: temporal-development
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
      - TEMPORAL_NAMESPACE=test
      - TEMPORAL_HOST=temporal:7233
    build: ./
    networks:
      - temporal-network
    volumes:
      - ./:/temporal:z,rw
    stdin_open: true
    tty: true

  temporal-web:
    container_name: temporal-web
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    image: temporalio/web:1.15.0
    networks:
      - temporal-network
    ports:
      - "127.0.0.1:8088:8088"

  # Go workflow worker
  temporal-workflow-worker:
    container_name: temporal-workflow-worker
    build: ./
    working_dir: /temporal/workflow-worker
    entrypoint: ./worker --namespace default --host temporal:7233
    restart: always
    depends_on:
      - temporal
    networks:
      - temporal-network

  # Python activity worker
  temporal-activity-worker:
    container_name: temporal-activity-worker
    build: ./
    working_dir: /temporal/activity-worker
    entrypoint: python main.py --namespace default --host temporal:7233
    restart: always
    depends_on:
      - temporal
    networks:
      - temporal-network

networks:
  temporal-network:
    driver: bridge
    name: temporal-network
